name: Actualizar Agenda Diaria

on:
  schedule:
    - cron: '0 6 * * *'  # 06:00 AM UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
        
    - name: Ejecutar scraper
      run: python scraper.py
      
    - name: Commit y Push
      run: |
        git config --local user.email "github-actions@example.com"
        git config --local user.name "GitHub Actions"
        git add index.html
        git commit -m "Actualización automática" || echo "Sin cambios"
        git push
